version: "2"

services: 
    backend:
        build: .
        image: happyhour/backend
        ports:
            - "80:80"
            - "6080:6080"
        links:
            - database
    database:
        image: rethinkdb